#!/bin/bash
echo "=== Testing MM Reyting Tizimi ==="
echo ""
echo "1. Opening browser at http://localhost:8080/index.html"
echo "2. Check the following:"
echo "   ✓ 'Xo'jalik Profili' dropdown should have 5 options"
echo "   ✓ 'Yuqori Tashkilot' dropdown should be visible"
echo "   ✓ All KPI inputs should have default value 0"
echo ""
echo "3. Open browser console (F12) and check for:"
echo "   ✓ 'populateProfileSelect called'"
echo "   ✓ 'Added profile: ...' (5 times)"
echo "   ✓ 'Total options: 6' (1 default + 5 profiles)"
echo ""
echo "Server is running on port 8080"
echo "Press Ctrl+C to stop"
